spring.application.name=split-up
#spring.security.user.name=harish
#spring.security.user.password=mdHarish
#spring.security.user.roles=ADMIN


#Database

#spring.datasource.url=jdbc:postgresql://localhost:5332/splitup
#spring.datasource.username=harish-14997
#spring.datasource.password=Mohamed@001
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:h2:mem:splitup
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging for debugging
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=DEBUG

#caching properties
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.hibernate.cache.spi=DEBUG
spring.jpa.properties.hibernate.cache.spi.provider=org.ehcache.jsr107.EhcacheCachingProvider


